### ISSUE TITLE
Unifi Controller VM compatibility

### ISSUE THREAD

**Issue by FlexServ** [MassimilianoPasquini97/zbx_unifi_network#1]
How to define an alternative port (other than 443) for Unifi controller API access.
Tried setting the `{$UNIFI.IP}` macro value to something like: `10.0.0.1:8443` but that does not seem to work.

**Comment by MassimilianoPasquini97** [comment]
Hi @FlexServ,
this template work only using https on any port, are you using http?

Here how `{$UNIFI.IP}` is used on one of the three API resource used for fetching data.
![image](https://github.com/MassimilianoPasquini97/zbx_unifi_network/assets/62497822/e08a2095-40c5-4af4-9ad9-46b06840c6e8)

**Comment by FlexServ** [comment]
Hi @MassimilianoPasquini97 ,
We have a linux vm with Unifi Controller software installed and our API address is: https://10.0.0.1:8443/api/auth/login

If i set the `{$UNIFI.IP}` macro to `10.0.0.1:8443` i just noticed the error message changed to:
_The response code 401 did not match any of the required status codes "200"_

This suggests an authentication error, but we can login to the Controller with that user/password. Even using a 'Super Administrator' account gives a: _response code 401_

Does the template support the Unifi Controller software on a linux host?

**Comment by MassimilianoPasquini97** [comment]
This template was designed for Unifi Dream Machine, I haven't  tested with Unifi Controller software but probably could work.

Have you tried to access auth API using curl for better logging? If not try this step:

1. Create a JSON file container body request with your credential.
2.

**Comment by MassimilianoPasquini97** [comment]
This template was designed for Unifi Dream Machine, I haven't tested with Unifi Controller software but probably could work.

Have you tried to access auth API using curl for better logging? If not try this step:

1. Create a JSON file named *body.json* containing body request with your credential.
```json
{
	"username": "yourusername",
	"password": "yourpassword"
}
```
2. Use the following curl command and view the result.
```bash
curl -k -v -X POST -d @body.json --header 'Content-Type: application/json' https://10.0.0.1:8443/api/auth/login
```
3. If credential are correct, API respond setting up auth token on ```TOKEN``` cookie and responding with a JSON file with all information about user used on authentication. **DO NOT SHARE JSON RESPONSE OR COOKIE TOKEN THEY MIGHT CONTAIN SENSITIVE INFORMATION**

**Comment by MassimilianoPasquini97** [comment]
This Zabbix template was originally design for UDM only for monitoring my own UDM I have at home. 

I spin up a docker  container of Unifi Controller on my local machine and I notice not only auth uri differ between UDM and Unifi Controller (how [Ubiquiti Community Wiki](https://ubntwiki.com/products/software/unifi-controller/api#udm_pro_api) say), but it use different cookie for authentication, at a previous look it use `unifises` and `csrf_token` instead of `TOKEN` used by UDM.

With some work this template can be modified for support UDM and Unifi Controller. When I will have some spare time I can work on it.

**Comment by MassimilianoPasquini97** [comment]
Hi @FlexServ,
I have updated both template on dev branch:

- [zbx_template_unifi_network for 6.4](https://raw.githubusercontent.com/MassimilianoPasquini97/zbx_unifi_network/dev/6.4/zbx_template_unifi_network.yaml)
- [zbx_template_unifi_network for 6.2](https://raw.githubusercontent.com/MassimilianoPasquini97/zbx_unifi_network/dev/6.2/zbx_template_unifi_network.yaml)

By default it work for Unifi Dream Machine Pro, for using it on a Unifi Controller you need to modify those macros:

- ***{$UNIFI.API.AUTH.URI}***: change to `api/login`.
- ***{$UNIFI.API.AUTH.TOKEN}***: change to `unifises`.
- ***{$UNIFI.API.URI}***: change to `api/s/default/stat`.

Tell me if it work and keep in mind that not all items supported on Unifi Dream Machine Pro is supported by Unifi Controller VM.

**Comment by FlexServ** [comment]
Hi @MassimilianoPasquini97,
Really nice, things are starting to work!

As you said, not all items are supported so there are quite a few:
> Failed: cannot extract value from json by path "<some_expression_here>": no data matches the specified path
...but this seems harmless as Zabbix automatically sets the item status to 'Not supported'

The only thing i got is some 'false positives' on the "Problem on WAN" and "Problem on VPN" triggers because the 'Unifi WAN Status' and 'Unifi VPN Status' is: `unknown`
Don't know if this could be addressed by adjusting the trigger ...i've just disabled them for now.


Thanks for adding this!

**Comment by MassimilianoPasquini97** [comment]
I have fixed false positive on the following triggers:

- Problem on WAN
- Problem on WLAN
- Problem on LAN
- Problem on VPN

Al changes was merged on main branch.
