### ISSUE TITLE
[BUG] Cannot evaluate function last(/Unifi Controller/unifi.health,#3): item history is disabled.

### ISSUE THREAD

**Issue by djrarky** [MassimilianoPasquini97/zbx_unifi_network#11]
## Checklist

- [X] I'm using the latest Zabbix Server Release.
- [X] I'm using a local UniFi Account with at least RO permission on Zabbix.
- [X] I have configured the template following README.md instruction.

## Describe the Bug

I've managed to add the template and pull resources, however the trigger Unifi API Not Responding has the following error message:
`Cannot evaluate function last(/Unifi Controller/unifi.health,#3): item history is disabled.`

I apologise, I'm new to Zabbix, I'm wondering if this should work out of the box, or needs additional configuration. 
For reference, I'm using a unifi controller. 
![image](https://github.com/MassimilianoPasquini97/zbx_unifi_network/assets/10834935/709be54e-6590-4e81-b124-a93451ef48d6)

- Zabbix Template Release: `main`
- Zabbix Server Release: `6.4.7`
- UniFi Network Release: `8.0.7`
- UniFi Network Type: `VM`

**Comment by MassimilianoPasquini97** [comment]
Hi @djrarky,
thank for your bug report. I have deleted 'Unifi API not responding' trigger on d7c6ab6a78f9e71ccc864d4bb545a3138668d6da, without history 'unifi.health' cannot be used for triggers.
