### ISSUE TITLE
Template not retrieving data

### ISSUE THREAD

**Issue by rpgmanx** [MassimilianoPasquini97/zbx_unifi_network#14]
## Checklist

- [ 6.2.6 ] I'm using the latest Zabbix Server Release.
- [ X ] I'm using a local UniFi Account with at least RO permission on Zabbix.
- [ X ] I have configured the template following README.md instruction.

## Describe the Bug

First of all, thanks for your incredible work, I'm craving to see it working.

I've just started trying to configure the template on a Unifi Network VM, I've tested the credentials (user named zabbix with RO) with Postman receiving an OK in the API request but Zabbix is telling me that error and is not working:

![Zabbix Unifi 1](https://github.com/MassimilianoPasquini97/zbx_unifi_network/assets/104001203/ec56d428-6397-4d4f-830a-71d52e5a25c4)

Do you even mind why it is failing?

I would appreciate your help with that.

## MACROS
![Zabbix Unifi 3](https://github.com/MassimilianoPasquini97/zbx_unifi_network/assets/104001203/849943d6-f18f-45c8-978b-7b7cfa8ca55a)

## Context

- Zabbix Template Release: `ex. main`
- Zabbix Server Release: `ex. 6.2.6`
- UniFi Network Release: `ex. 8.0.26`
- UniFi Network Type: `VM`

**Comment by MassimilianoPasquini97** [comment]
Hi @rpgmanx,
from your screenshot it appear API requests are working correctly otherwise you would see an error on Item with tags 'Application: raw' and UAP items would not be generated.

You are facing this issue only on one host? From your screen the error could be only on one UAP host.
