### ISSUE TITLE
[PROBLEM]  Cannot change port

### ISSUE THREAD

**Issue by johnmacdowall** [MassimilianoPasquini97/zbx_unifi_network#15]
## Checklist

- [x ] I'm using the latest Zabbix Server Release.
- [x ] I'm using a local UniFi Account with at least RO permission on Zabbix.
- [x ] I have configured the template following README.md instruction.

## Context

- Zabbix Template Release: `main`
- Zabbix Server Release: `ex. 6.4.7`
- UniFi Network Release: `ex. 8.0.7`
- UniFi Network Type: `VM`

root@unifi:/etc# netstat -avpnt | grep 443
tcp6       0      0 :::8443                 :::*                    LISTEN      242/java
tcp6       0      0 192.168.1.45:8443       192.168.1.19:60095      ESTABLISHED 242/java
tcp6       0      0 192.168.1.45:8443       192.168.1.19:60097      ESTABLISHED 242/java
root@unifi:/etc#

I'm running unifi in a self-hosted (proxmox) VM.  I cannot change the HTTP port in the java app or in your template.

Is there a way?

**Comment by MassimilianoPasquini97** [comment]
Hi @johnmacdowall,
on `{$UNIFI.IP}` macro you can set an alternative port from the default 443. In your case you need to set this macro with `192.168.1.45:8443` value.
