### ISSUE TITLE
[BUG] Clients showing as {#NAME}

### ISSUE THREAD

**Issue by longhornwhistler** [MassimilianoPasquini97/zbx_unifi_network#16]
## Checklist

- [X] I'm using the latest Zabbix Server Release.
- [X] I'm using a local UniFi Account with at least RO permission on Zabbix.
- [X] I have configured the template following README.md instruction.

## Describe the Bug

Clients are showing as {#NAME} instead of the actual client name.

<img width="968" alt="Screenshot 2024-03-12 at 10 47 36 AM" src="https://github.com/MassimilianoPasquini97/zbx_unifi_network/assets/13263841/70873883-cee4-4a22-b479-bf6670f834cc">

## MACROS

<img width="718" alt="Screenshot 2024-03-12 at 10 49 13 AM" src="https://github.com/MassimilianoPasquini97/zbx_unifi_network/assets/13263841/240a221a-33ed-4776-91f5-b8f4f30122c3">
<img width="984" alt="Screenshot 2024-03-12 at 10 49 02 AM" src="https://github.com/MassimilianoPasquini97/zbx_unifi_network/assets/13263841/cfc8dd52-a8a7-4067-8a20-d57b4ffe6dd2">
<img width="709" alt="Screenshot 2024-03-12 at 10 49 32 AM" src="https://github.com/MassimilianoPasquini97/zbx_unifi_network/assets/13263841/bf5ec020-c2eb-4c0f-bd37-cf53d5091025">
<img width="696" alt="Screenshot 2024-03-12 at 10 49 22 AM" src="https://github.com/MassimilianoPasquini97/zbx_unifi_network/assets/13263841/e51baf9b-88f7-4910-8b13-f7f4090a24d7">

## Context

- Zabbix Template Release: Main
- Zabbix Server Release: 6.4.10
- UniFi Network Release: 8.0.28
- UniFi Network Type: Dream Machine

**Comment by cawhite6** [comment]
Issue lies with the JSON returned with current Network App 8.0+ - if you have NOT manually set a connected client name in the UI Network App, then that field is never returned. Update the LLD MARCO #NAME in the template for Wired and Wireless clients discovery to 'hostname' field. Now issue is if you do manually set a name in clients then hostname is returned as "" (blank) and name field is generated. I'm trying to work on a way to basically do an IF/THEN with LLD to fix this but don't know if it's possible. IF hostname ="" then parse 'name' field for LLD MACRO #NAME.

Hope this helps the 99% it did for me...... excellent work on this template btw!

**Comment by MassimilianoPasquini97** [comment]
Hi @cawhite6, thanks for your report, any help is appreciated. One way to solve this issue could be adding a simple custom JavaScript at preprocessing stage on the discovery rule. The script need to check if **name** is defined and in case it isn't it define **name** with **hostname** value.

**Comment by ketomagasaki** [comment]
Hello,

I've just set up the template, and I'm facing the same issue, with the following specifications:

- Zabbix Template Release: Main
- Zabbix Server Release: 6.4.13
- UniFi Network Release: 8.1.113
- UniFi Network Type: Dream Machine SE

But I also have another issue that might be related.
I'm missing 2 switches in the discovery, and I found these errors:

![image](https://github.com/MassimilianoPasquini97/zbx_unifi_network/assets/54591921/5d7c79a0-5c35-4a64-909f-ff1f5ccdc2a4)

**Comment by MassimilianoPasquini97** [comment]
I have fixed the issue with empty {#NAME} LDD macron on c8f653f8e65a536b93f59331645733bdc4e6e406. I have solved that with a Custom JavaScript that define 'name' value with 'hostname' if undefined.

**Comment by MassimilianoPasquini97** [comment]
@ketomagasaki Is your USW device containing '{' character?

**Comment by ketomagasaki** [comment]
Thank you for the correction c8f653f, I no longer have the client value with {#NAME} 😊

No, the names of the 2 missing USWs are:

- USW-Aggregation
- USW-Pro-24-PoE

I posted here because the error message is `Cannot create host "Unifi USW {#NAME}": name contains invalid character '{`. So, since there's also an issue with {#NAME}, I thought it might be the same problem.

**Comment by ketomagasaki** [comment]
I analyzed the API call and indeed for these 2 USWs, there is no name returned.

![image](https://github.com/MassimilianoPasquini97/zbx_unifi_network/assets/54591921/4027cad2-b004-42d7-b57c-714cddc691a0)

I simply changed their names and then put back the original ones, now their names appear in the JSON. A bug in the API apparently 🤔

It's good for me, thank you for your help 👍

**Comment by MassimilianoPasquini97** [comment]
Released version [c8f653f](https://github.com/MassimilianoPasquini97/zbx_unifi_network/releases/tag/c8f653f) containing the fix.
