### ISSUE TITLE
[BUG] Default named devices are not being auto-discovered

### ISSUE THREAD

**Issue by triplesix2001** [MassimilianoPasquini97/zbx_unifi_network#18]
## Checklist
- [*] I'm using the latest Zabbix Server Release.
- [*] I'm using a local UniFi Account with at least RO permission on Zabbix.
- [*] I have configured the template following README.md instruction.

## Describe the Bug
Default named switches or AP's are not being auto-discovered.

## MACROS
![image](https://github.com/MassimilianoPasquini97/zbx_unifi_network/assets/107557402/626f689c-6cb6-4995-8d89-2510f6165cd0)

## Context
- Zabbix Template Release: main
- Zabbix Server Release: 6.4.13
- UniFi Network Release: 8.1.113
- UniFi Network Type: Dream Machine Pro

**Comment by triplesix2001** [comment]
Did some more testing and would like to clarify that unchanged naitive names are not being auto-discovered. If i change the standard name of an AP and then change it back i can discover it with no problem.

**Comment by MassimilianoPasquini97** [comment]
Already discussed in #16
