### ISSUE TITLE
switch to a different site in Zabbix?

### ISSUE THREAD

**Issue by lschretlen** [MassimilianoPasquini97/zbx_unifi_network#19]
Hi,

Question: we have a local Unifi Controller running but we have different Sites within the controller.
For some reason Zabbix is only seeing the first (default) site.

Is there a way to point Zabbix to a different site then the default site?
If Yes can you tell how to do this?

**Comment by MassimilianoPasquini97** [comment]
Hi @lschretlen, this template was originally design for Unifi Dream Machine and than adapted to work with Unifi Network in VM. At this stage doesn't support multiple sites.
