### ISSUE TITLE
[BUG] No values are received but devices are.

### ISSUE THREAD

**Issue by Hunv** [MassimilianoPasquini97/zbx_unifi_network#20]
## Checklist

- [X] I'm using the latest Zabbix Server Release. => 6.4.12
- [X] I'm using a local UniFi Account with at least RO permission on Zabbix. => A controller VM
- [X] I have configured the template following README.md instruction.

## Describe the Bug

I configured the settings and the devices are discovered. But the devices and also the "dummy host" for the Network Manager do not have any values.
Two questions that may be an issue but I want to verify:
1. Is only port 8443 (where the website runs) required from the Zabbix Server to the UniFi Network Server or are other connections required (i.e. other ports or connections to the devices itself)?
2. Is it possible that the ~half year old Network Server is the problem?

## MACROS

![image](https://github.com/MassimilianoPasquini97/zbx_unifi_network/assets/10775372/1deae9ca-ae42-4447-8496-9651bd71fa4b)

## Context

- Zabbix Template Release: `main`
- Zabbix Server Release: `6.4.12`
- UniFi Network Release: `7.5.187` (Ubiquiti Network Server VM)
- UniFi Network Type: `VM`

**Comment by MassimilianoPasquini97** [comment]
Hi @Hunv,

1. Yes, the template it only use Unifi Network API.
2. It could be, the template it was tested with le latest Unifi Network Version.

Can you provide me more information like errors received from empty items?

**Comment by MassimilianoPasquini97** [comment]
Closed by inactivity
