### ISSUE TITLE
[BUG] Dont see the devices or the date from them 

### ISSUE THREAD

**Issue by izhelev83** [MassimilianoPasquini97/zbx_unifi_network#21]
## Checklist

- [X] I'm using the latest Zabbix Server Release.
- [X] I'm using a local UniFi Account with at least RO permission on Zabbix.
- [X] I have configured the template following README.md instruction.

## Describe the Bug
In all items and triggers i get error in zabbix 

Preprocessing failed for: {}
1. Failed: cannot extract value from json by path "$.data[1].['gw_system-stats'].cpu": no data matches the specified path
and that is from Triggers 
Cannot evaluate function avg(/UDM-PRO/unifi.cpu,{$UNIFI.CPU.USAGE.HIGH.SEC}): item is not supported.

and that is from DIsovery on all devices get that 

Preprocessing failed for: {}
1. Failed: cannot extract value from json by path "$.data": no data matches the specified path

## MACROS

Screenshot of configured MACROS.
![Screenshot 2024-05-12 120404](https://github.com/MassimilianoPasquini97/zbx_unifi_network/assets/156476740/3d41f8bf-7da1-44ab-bbc2-0698b6558ca7)

## Context

- Zabbix Template Release: `ex. main`
- Zabbix Server Release:  ' 6.4.14`
- UniFi Network Release: `8.1.127`
- UniFi Network Type: `Dream Machine`

**Comment by MassimilianoPasquini97** [comment]
Hi @izhelev83,
are you having this issue on all items? if yes, this could be a problem related with provided credential or network reaching. Be sure that provided credentials work with the correct permission and that the Zabbix Server can reach the Unifi Dream Machine. 

For better troubleshooting I will need errors provided from those items:
- Unifi Network: API stat/sta
- Unifi Network: API stat/health
- Unifi Network: API stat/device-basic

**Comment by MassimilianoPasquini97** [comment]
Closed by inactivity
