### ISSUE TITLE
[BUG] Zabbix 7

### ISSUE THREAD

**Issue by pax0707** [MassimilianoPasquini97/zbx_unifi_network#23]
I know it's just released but just to note it's not working on Zabbix 7.

Preprocessing failed for: {}
1. Failed: cannot extract value from json by path "$.data[1].['gw_system-stats'].cpu": no data matches the specified path

**Comment by MassimilianoPasquini97** [comment]
Hi @pax0707,
that error is not related to the used Zabbix version. I'm using the 6.4 version of this template on Zabbix 7.0 from two week and I didn't find any issue. I have added official support to 7.0 from [68f3be2](https://github.com/MassimilianoPasquini97/zbx_unifi_network/releases/tag/68f3be2) release.
