### ISSUE TITLE
Port 443 Access??

### ISSUE THREAD

**Issue by stevefxp1** [MassimilianoPasquini97/zbx_unifi_network#28]
## Checklist

- [X] I'm using the latest Zabbix Server Release.
- [X] I'm using a local UniFi Account with at least RO permission on Zabbix.
- [X] I have configured the template following README.md instruction.

## Describe the Bug

After adding your template I am getting the following: Cannot perform request: Failed to connect to 192.168.2.100 port 443 after 0 ms: Couldn't connect to server. It should be port 8443, which is the default port.

## MACROS

![Screenshot 2024-07-26 115343](https://github.com/user-attachments/assets/5f924f4e-25d7-4488-b9d1-c5e897162132)

## Context

- Zabbix Template Release: zbx_template_unifi_network.yaml
- Zabbix Server Release: 7.0.1
- UniFi Network Release: 8.3.32
- UniFi Network Type: Self hosted controller VM running Ubuntu 22.04 and Unifi software 8.3.32

**Comment by MassimilianoPasquini97** [comment]
If your are using port 8443 append ":8433" on ip. Please read the documentation before open useless issues.

**Comment by stevefxp1** [comment]
Before you send me a blast response how about showing me where it says to use the port on the IP. Right from your main page: **{$UNIFI.IP}: IP or FQDN of Unifi Network Web Interface.**

Tell me where in that statement it says to use the port?

**Comment by MassimilianoPasquini97** [comment]
@stevefxp1 before opening an issue at least search throw past issues if someone had the same issue. #15

**Comment by stevefxp1** [comment]
I believe I did but if I missed a prior ticket I apologize. This still does not give you the right to flame me in your response, especially when your instructions are dead wrong.Sent from my T-Mobile 5G Device
-------- Original message --------From: Massimiliano Pasquini ***@***.***> Date: 7/27/24  13:11  (GMT-05:00) To: MassimilianoPasquini97/zbx_unifi_network ***@***.***> Cc: stevefxp1 ***@***.***>, Mention ***@***.***> Subject: Re: [MassimilianoPasquini97/zbx_unifi_network] Port 443 Access?? (Issue #28) 
@stevefxp1 before opening an issue at least search throw past issues if someone had the same issue. #15
