### ISSUE TITLE
[Enhancement] Write some developer documentation

### ISSUE THREAD

**Issue by lxndrp** [MassimilianoPasquini97/zbx_unifi_network#33]
I'd very much like to contribute, but although I am a seasoned Zabbix administrator with some experience in writing UserParameter scripts and LLD, I find it very hard to understand how things connect together in your template.

As such, it would be much appreciated if you could do a small writeup on how things hook together.

Thanks in advance!

**Comment by MassimilianoPasquini97** [comment]
Hi @lxndrp, 
Comparing Zabbix templating to developing requires courage 😅. While it includes some JavaScript lines for retrieving data from APIs and basic post-processing, the majority of the template relies on LLD (Logic Level Data) and Dependent Items. This simple template doesn't necessitate a "developer" documentation, even Unifi APIs aren't officially documented.
