### ISSUE TITLE
[BUG] Unifi OS 4.0.6 on UDM PRO Not getting device details

### ISSUE THREAD

**Issue by roalvesrj** [MassimilianoPasquini97/zbx_unifi_network#34]
## Checklist

- [X] I'm using the latest Zabbix Server Release.
- [X] I'm using a local UniFi Account with at least RO permission on Zabbix.
- [X] I have configured the template following README.md instruction.

## Describe the Bug

When using the template with Network Application 8.4.54 / Unifi OS 4.0.6, the device details are not displayed, giving the error:

> Preprocessing failed for: {}
> 1. Failed: cannot extract value from json by path "$.data[0].adopted": no data matches the specified path

![image](https://github.com/user-attachments/assets/4ad41cee-462b-4427-90ef-cdd4490910f5)

I saw that there was a problem [here](https://github.com/MassimilianoPasquini97/zbx_unifi_network/issues/22) recently with Unifi OS 4.0.3, is it possible that it is a similar problem?

## MACROS

![image](https://github.com/user-attachments/assets/a6f182b9-f8c2-4b10-8343-ba667be65269)

## Context

- Zabbix Template Release: `ex. main`
- Zabbix Server Release: `7.0.2`
- UniFi Network Release: `8.4.54`
- UniFi Network Type: `UDMP 4.0.6`

**Comment by MassimilianoPasquini97** [comment]
Hi @roalvesrj,
I was experiencing the same issue using Zabbix Server 7.0.2. After a little bit of troubleshooting, it seems like it was a bug related to the "HTTP agent" on that specific Zabbix Server version that caused the error. Today I have upgraded Zabbix Server to 7.0.3 and it solved the issue.

Can you try to do the same and let me know if it solves the issue? Thanks 🙏🏻

**Comment by TyzzyT** [comment]
I experienced the same problem, but it's working now with Zabbix server 7.0.3

**Comment by MassimilianoPasquini97** [comment]
Zabbix Server 7.0.3 release solve this issue.

**Comment by SergeyLeongard** [comment]
I have the same error on zabbix 7.0.4 server
![image](https://github.com/user-attachments/assets/25a19c9f-be15-4316-9169-383aa9e80144)
