### ISSUE TITLE
Add makro for different sites

### ISSUE THREAD

**Issue by JustLukassss** [MassimilianoPasquini97/zbx_unifi_network#35]
Template doesnt find devices that are under different site. There is different URL.
![image](https://github.com/user-attachments/assets/7801a89d-e3ac-4887-85cb-8c08e4c8c104)
![image](https://github.com/user-attachments/assets/33d21b7b-b304-41c5-b8f2-e03a0518e625)

Instead of /Default/ probably some UUID is used.

Thank you Lukas.

**Comment by gonzalobellon** [comment]
Hi, +1 to this request, the template is awesome and site compatibility would be great! best regards.

**Comment by SergeyLeongard** [comment]
Привет, +1 к этому запросу, шаблон потрясающий и совместимость с сайтом была бы отличной!
В то же время, как я могу дублировать шаблон, чтобы использовать его на разных сайтах?
С наилучшими пожеланиями.

**Comment by dalezorz** [comment]
+1 for this request.

**Comment by dalezorz** [comment]
> Template doesnt find devices that are under different site. There is different URL. ![image](https://private-user-images.githubusercontent.com/179919932/363096788-7801a89d-e3ac-4887-85cb-8c08e4c8c104.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTAwNTcsIm5iZiI6MTczMTQ4OTc1NywicGF0aCI6Ii8xNzk5MTk5MzIvMzYzMDk2Nzg4LTc4MDFhODlkLWUzYWMtNDg4Ny04NWNiLThjMDhlNGM4YzEwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QwOTIyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTA4Yjc4MWU3MmIzMDQ2OTM1MTU5OTYyYjY1YmZkOGQ1ZDJjNzUzNjk1OGQzYTRlYjE1M2QyOGQzM2U5MzFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.o2zjieD5SOXpXilhQT1O5kcdfSVbiKPsdatXlowvH_Q) ![image](https://private-user-images.githubusercontent.com/179919932/363097045-33d21b7b-b304-41c5-b8f2-e03a0518e625.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTAwNTcsIm5iZiI6MTczMTQ4OTc1NywicGF0aCI6Ii8xNzk5MTk5MzIvMzYzMDk3MDQ1LTMzZDIxYjdiLWIzMDQtNDFjNS1iOGYyLWUwM2EwNTE4ZTYyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QwOTIyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2UxOTcwZjUwMjBiMzhkMTkzZGM0ZTA0NGNhMWJhOTkwNjg5MzNlN2EzMWYyYTNlZmYxODg2YzIzYzU2NGE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.O04_O9aeaD2EGbV_l1dxHck3izT2cOsiufgQPFZunXg)
> 
> Instead of /Default/ probably some UUID is used.
> 
> Thank you Lukas.

Hi Lukas,

I believe you add/change the following in the config to change the site from personal to something else.
Just ensure the Unifi user account has access to the site that you want to monitor.

<img width="534" alt="Screenshot 2024-11-13 at 11 25 10 AM" src="https://github.com/user-attachments/assets/7440a143-be94-42ed-a5d0-7c58d81e9b93">


<img width="430" alt="Screenshot 2024-11-13 at 11 26 37 AM" src="https://github.com/user-attachments/assets/6bbb6e94-5455-4160-b1ff-a14fd9b7095f">

**Comment by gonzalobellon** [comment]
Hi everyone. Indeed, if you replace the word 'default' with the site ID, you can monitor the devices of that site. But, if you want to monitor another site in the same controller, you can't. This is what I'm looking for, I have several sites in my controller, but I can only monitor one. Perhaps you can clone the template, but I don't know how. I appreciate your help. Best regards.

**Comment by dalezorz** [comment]
> Hi everyone. Indeed, if you replace the word 'default' with the site ID, you can monitor the devices of that site. But, if you want to monitor another site in the same controller, you can't. This is what I'm looking for, I have several sites in my controller, but I can only monitor one. Perhaps you can clone the template, but I don't know how. I appreciate your help. Best regards.

@gonzalobellon just add a new host and use the same template, just modify the "default" to the new site ID. It will be the same host IP but give the new host the name of the secondary site. Then repeat for the third and fourth sites etc.

**Comment by gonzalobellon** [comment]
> > Hi everyone. Indeed, if you replace the word 'default' with the site ID, you can monitor the devices of that site. But, if you want to monitor another site in the same controller, you can't. This is what I'm looking for, I have several sites in my controller, but I can only monitor one. Perhaps you can clone the template, but I don't know how. I appreciate your help. Best regards.
> 
> @gonzalobellon just add a new host and use the same template, just modify the "default" to the new site ID. It will be the same host IP but give the new host the name of the secondary site. Then repeat for the third and fourth sites etc.

Hi dalezorz, thanks for your response. I did as you say, but I'm getting this error: Preprocessing failed for: {}
1. Failed: cannot extract value from json by path "$.data[3].num_pending": no data matches the specified path

I'm using the same template, the first created site work, but 2 others don't. 
I'm using the same variables, with the only exception of '{$UNIFI.API.URI}', where I set matching the site ID. 

Regards.

**Comment by dalezorz** [comment]
@gonzalobellon Did you add your Unifi user account to all of the sites you are wanting to monitor via Zabbix?

**Comment by gonzalobellon** [comment]
> @gonzalobellon Did you add your Unifi user account to all of the sites you are wanting to monitor via Zabbix?

Yes, same username and password for all sites.

**Comment by gonzalobellon** [comment]
> > @gonzalobellon Did you add your Unifi user account to all of the sites you are wanting to monitor via Zabbix?
> 
> Yes, same username and password for all sites.

I just noticed that I didn't create the user account in the other sites, I will try this and keep you posted.
Thanks for pointing me in the right direction! Regards

**Comment by gonzalobellon** [comment]
> > > @gonzalobellon Did you add your Unifi user account to all of the sites you are wanting to monitor via Zabbix?
> > 
> > 
> > Yes, same username and password for all sites.
> 
> I just noticed that I didn't create the user account in the other sites, I will try this and keep you posted. Thanks for pointing me in the right direction! Regards

Worked. Thank you!!

**Comment by MassimilianoPasquini97** [comment]
Thank to all of you 🙏🏻. I have added a section on the README.md that explains how to configure multiple sites based on this issue information.
