### ISSUE TITLE
Zabbix shows only one AP

### ISSUE THREAD

**Issue by IKILLER147** [MassimilianoPasquini97/zbx_unifi_network#37]
Hi, I added a new guest according to the instructions, which refers to Unifi Controller in the macros, I used Unifi AP as a template. Everything works fine, but it only loads the data of 1 AP out of 15, what am I doing wrong? Do I need to do the configuration for each AP separately?

Thank you for your help
![Zabbix](https://github.com/user-attachments/assets/aa558496-29e7-4ecd-b8b3-9a3075c36ede)

**Comment by MassimilianoPasquini97** [comment]
Hi @IKILLER147,
the template auto discover all AP, check that you are using the latest template version from main.
