### ISSUE TITLE
Uplink speed for UAP and USW

### ISSUE THREAD

**Issue by Isilorn** [MassimilianoPasquini97/zbx_unifi_network#4]
Hello,

I'm deploying Zabbix for my home network and I discovered your template... Great work and I love it 😄 

I've got some connectivity issues that I'd like to trace. Would it be possible to add the uplink speed or "Experience" (10 GbE, GbE, FE) in the informations pulled from the devices ?

<img width="355" alt="image" src="https://github.com/MassimilianoPasquini97/zbx_unifi_network/assets/7522688/2b52e353-2c27-447d-b12e-cd0131b6e529">

**Comment by MassimilianoPasquini97** [comment]
Hi @Isilorn,

as requested I have integrated uplink speed items on templates for UAP and USW devices with triggers fires on speed change. New templates are now available on  [uplink_speed](https://github.com/MassimilianoPasquini97/zbx_unifi_network/tree/uplink_speed) branch and will be merged on main on further test. Let me know if there are some issues.

**Comment by Isilorn** [comment]
Thanks a lot, just updated the template I'll let you know if I run into any issue 😄
