### ISSUE TITLE
[BUG] Wireless Total rx Retries and Wireless Total tx Retries named incorrectly

### ISSUE THREAD

**Issue by daanfleuren** [MassimilianoPasquini97/zbx_unifi_network#41]
### Checklist

 I am using the latest Zabbix Server release.
 I am using a local UniFi account with at least Read-Only (RO) permission on Zabbix.
 I have configured the template according to the instructions in the README.md.

### Bug Description
A clear and concise description of the bug. If applicable, include screenshots to help explain the problem.

The item prototypes [Wireless Total rx Retries] and [Wireless Total tx Retries] in the discovery rule "API stat/sta: Client Wireless" are incorrectly categorized and named. The "r" in the JSON parameters tx_bytes-r and rx_bytes-r stands for rate, not retries.

Please review these sources:
https://community.ui.com/questions/How-to-Read-wanrxbytes-Unifi-Controller-API/ff93ac0e-96d4-49fc-8379-741e7cf072f3
https://github.com/unpoller/unifi/issues/33

**Comment by MassimilianoPasquini97** [comment]
Hi @daanfleuren,
thanks you for opening this issue, I have solved that on 2751cdc commit
