### ISSUE TITLE
[New Device] UDR

### ISSUE THREAD

**Issue by maddingamer** [MassimilianoPasquini97/zbx_unifi_network#42]
UniFi OS 4.0.6 adds support for SNMP on UDR

## Context

- UniFi Device Type: `UDR`
- UniFi Device Name: [UDR](https://eu.store.ui.com/eu/en/products/udr)

## New Features

Same items and triggers as UDM combined with UAP would be good I guess.

## JSON

attached as file for better view
[udr.json](https://github.com/user-attachments/files/17482076/udr.json)

**Comment by MassimilianoPasquini97** [comment]
Hi @maddingamer,
this template doesn't use SNMP for monitoring instead it use the local HTTPS API.

**Comment by maddingamer** [comment]
Sorry for the confusion about snmp. Could you add the udr to the template using http api?

**Comment by evant89** [comment]
Hello,

Would it be possible to extend support to include UCG and UXG devices as well?

Thank you!
