### ISSUE TITLE
[BUG] Title

### ISSUE THREAD

**Issue by misteradamx** [MassimilianoPasquini97/zbx_unifi_network#43]
## Checklist

- [X] I'm using the latest Zabbix Server Release.
- [X] I'm using a local UniFi Account with at least RO permission on Zabbix.
- [X] I have configured the template following README.md instruction.

## Describe the Bug
Getting the following error:
`
Preprocessing failed for: {"header":{"HTTP/2 200":"","server":"nginx","date":"Fri, 01 Nov 2024 05:32:34 GMT","content-type"...
1. Failed: cannot perform regular expression "$TOKENISHERE=([^;]+);" match for value of type "none": pattern does not match
`

I used `curl -k -X POST --data '{"username": "root", "password": "$password"}' --header 'Content-Type: application/json' -c cookie.txt https://192.168.1.1:443/api/auth/login` to get the Token. Is there a better method?

## MACROS

![firefox_OnLU9zwmyD](https://github.com/user-attachments/assets/2ff1d189-bc5c-4e31-b755-0b4ba8c55882)

## Context

- Zabbix Template Release: `main`
- Zabbix Server Release: `7.0.5`
- UniFi Network Release: `8.5.6 or UniFi OS 4.0.21`
- UniFi Network Type: `Dream Machine SE`

**Comment by MassimilianoPasquini97** [comment]
From documentation.

> {$UNIFI.API.AUTH.TOKEN}: change to unifises if using unifi controller vm

**Comment by misteradamx** [comment]
That explicitly says "unifi controller vm", I am not using a VM, I am using a UDM SE.
