### ISSUE TITLE
[BUG] Discovery doesn't seem to work

### ISSUE THREAD

**Issue by mrdmiller2** [MassimilianoPasquini97/zbx_unifi_network#45]
## Checklist

- [X] I'm using the latest Zabbix Server Release.
- [X] I'm using a local UniFi Account with at least RO permission on Zabbix.
- [X] I have configured the template following README.md instruction.

## Describe the Bug

Well in short.. its not discovering any devices.. And in the logs, its just a series of "unable to resolve name". I think its expecting a IP on port 80 rather than an external website on 8443.  The devices are internal, but the controller we have hosted externally so we can support multiple locations without VPN connections.

## MACROS
<img width="978" alt="Screenshot 2024-11-17 at 22 43 05" src="https://github.com/user-attachments/assets/50da8020-aa98-4646-b867-4b5f9fa7883a">

## Context

- Zabbix Template Release: `ex. main`
- Zabbix Server Release: `ex. 7.0.1'
- UniFi Network Release: `ex. 8.6.9`
- UniFi Network Type: `AP's, NX-Pro, and Switches`

**Comment by mrdmiller2** [comment]
One other observation,

When I go into the discovery rule list, I see:

<img width="1167" alt="Screenshot 2024-11-17 at 22 49 38" src="https://github.com/user-attachments/assets/ae15522c-402d-47eb-80c6-c15390e0c59d">

This sort of implies the discovery function doesn't work in on the 7.0.5 release

**Comment by MassimilianoPasquini97** [comment]
You are not using the latest Zabbix Release
