### ISSUE TITLE
Usage in Zabbix 6.0 LTS

### ISSUE THREAD

**Issue by mkvtsnl** [MassimilianoPasquini97/zbx_unifi_network#5]
Would it be possible to edit this template so it's possible to use this in Zabbix 6.0 LTS?

**Comment by MassimilianoPasquini97** [comment]
As mentioned here https://github.com/MassimilianoPasquini97/zbx_unifi_network/issues/3, this template is only available and tested on Zabbix 6.2 or above versions.
