### ISSUE TITLE
AP and switch renaming

### ISSUE THREAD

**Issue by Isilorn** [MassimilianoPasquini97/zbx_unifi_network#7]
Hello,

I apologize in advance for my question as I'm relatively new to Zabbix.

During a maintenance operation this weekend, I performed the following:

- Renamed an access point (due to its relocation).
- Renamed a switch (similarly) and changed its IP address.

In Zabbix, I still see the hosts with their old names, and the switch is shown as unreachable, even though it is fully accessible in reality.

I was considering deleting the hosts and allowing the discovery process to recreate them. Is this the right approach?

Thanks for your help.

**Comment by MassimilianoPasquini97** [comment]
Hi @Isilorn,
yes, in this case deleting the old one and let the template to automatically recreate them is the right approach.
