### ISSUE TITLE
Unable to set up

### ISSUE THREAD

**Issue by stefantrav** [MassimilianoPasquini97/zbx_unifi_network#8]
hello i have some trouble setting it up
i've used your instructions but i am getting this error

![image](https://github.com/MassimilianoPasquini97/zbx_unifi_network/assets/35542705/0beb5c20-3bac-4193-9caf-ba1858c70a4b)

**Comment by MassimilianoPasquini97** [comment]
Hi @stefantrav,
you are providing wrong credential, 401 error code stand for Unauthorised request. You need to create a local user on Unifi network with read permission and without 2FA.
